#!/bin/bash

class=
case $1 in
  polymult) class=PolyMult ;;
  factor) class=Factor ;;
esac

if [[ -z $class ]]; then
  exec ./gradlew run -q
else
  shift
  exec ./gradlew run -q -PmainClass="edu.cwu.cs301.bb010g.pr1.${class}P1" "$@"
fi
