/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bb010g' at '10/3/16 1:42 PM' with Gradle 2.14.1
 *
 * @author bb010g, @date 10/3/16 1:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
